version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080" # Using 8180 to avoid conflict with spring boot app
    depends_on:
      - postgres
    command:
      - "start-dev"

  keycloak-cli:
    image: adorsys/keycloak-config-cli:latest
    container_name: keycloak-cli
    volumes:
      - ./keycloak-config:/config
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      IMPORT_FILES_LOCATIONS: /config/realm-export.json
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: "true"
    depends_on:
      - keycloak

volumes:
  postgres_data:
