FROM mcr.microsoft.com/playwright:v1.45.0-jammy

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./
RUN pnpm install

COPY . .

# Skopiuj skrypt i nadaj mu uprawnienia do wykonania
COPY run-tests.sh .
RUN chmod +x run-tests.sh

# Ustaw skrypt jako domyślne polecenie
CMD ["./run-tests.sh"]
