sonar.projectKey=YOUR_ORGANIZATION_YOUR_PROJECT_KEY
sonar.organization=YOUR_ORGANIZATION
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,dist/**,.output/**,.nuxt/**,coverage/**,*.config.js,*.config.ts
